# build
FROM node:lts-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install -g cnpm --registry=https://registry.npm.taobao.org
RUN cnpm install
COPY /. ./
RUN npm run build

FROM php:8.1-apache-bullseye as deploy
ADD /apache/sources.list /etc/apt/
COPY --from=build /app/dist/ /var/www/html/
COPY /apache/000-default.conf /etc/apache2/sites-available/000-default.conf

RUN apt-get update; \
    apt-get install -y libldap2; \
    apt-get install -y mod_ldap; \
    apt-get install -y mod-authnz-ldap; \
    a2enmod ldap; \
    a2enmod authnz_ldap; 

CMD ["apache2-foreground"]