version: '3.5'

services:
  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - 3306:3306
    volumes:
      - "./mysql/data/:/var/lib/mysql"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    restart: always
  nextcloud_web:
    container_name: nextcloud_web
    # image: nextcloud
    build: ./
    ports:
      - 8061:80
      - 4433:443
    depends_on:
      - nextcloud_db
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    volumes:
      - "./nextcloud/data:/var/www/html" #./data是数据位置，可以修改
      - "./apache2/sites-available/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    restart: always
