version: '3.5'

services:
  nextcloud_db:
    container_name: nextcloud_db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    ports:
      - 3306:3306
    volumes:
      - "./data/mysql/:/var/lib/mysql"
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    restart: always
  nextcloud_web:
    container_name: nextcloud_web
    build: ./
    ports:
      - 8061:80
      - 4433:443
    depends_on:
      - nextcloud_db
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    volumes:
      - "./data/nextcloud:/var/www/html" #./data是数据位置，可以修改
      - "./docker-reference/000-default.conf:/etc/apache2/sites-available/000-default.conf"
    restart: always
