filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /home/logs/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true

output.elasticsearch:
  hosts: ["192.168.50.162:9200"]